// <auto-generated />
using System;
using GarageSaleApp.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GarageSaleApp.DataAccess.Migrations
{
    [DbContext(typeof(GarageSaleAppDbContext))]
    [Migration("20190214003708_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("GarageSaleApp.Domain.GarageSaleEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("EndDate");

                    b.Property<string>("Name");

                    b.Property<string>("Notes");

                    b.Property<DateTime?>("StartDate");

                    b.HasKey("Id");

                    b.ToTable("GarageSaleEvents");
                });

            modelBuilder.Entity("GarageSaleApp.Domain.GarageSaleEventParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color");

                    b.Property<int?>("EventId");

                    b.Property<int?>("PartyId");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PartyId");

                    b.ToTable("GarageSaleEventParties");
                });

            modelBuilder.Entity("GarageSaleApp.Domain.Party", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("GarageSaleApp.Domain.Payout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<DateTime>("DatePaid");

                    b.Property<int?>("EventPartyId");

                    b.HasKey("Id");

                    b.HasIndex("EventPartyId");

                    b.ToTable("Payouts");
                });

            modelBuilder.Entity("GarageSaleApp.Domain.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("EventId");

                    b.Property<DateTime>("TransactionDate");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("GarageSaleApp.Domain.SaleLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("PartyId");

                    b.Property<decimal>("Price");

                    b.Property<int?>("SaleId");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleLineItems");
                });

            modelBuilder.Entity("GarageSaleApp.Domain.GarageSaleEventParty", b =>
                {
                    b.HasOne("GarageSaleApp.Domain.GarageSaleEvent", "Event")
                        .WithMany("GarageSaleEventParties")
                        .HasForeignKey("EventId");

                    b.HasOne("GarageSaleApp.Domain.Party", "Party")
                        .WithMany("GarageSalesEventParties")
                        .HasForeignKey("PartyId");
                });

            modelBuilder.Entity("GarageSaleApp.Domain.Payout", b =>
                {
                    b.HasOne("GarageSaleApp.Domain.GarageSaleEventParty", "EventParty")
                        .WithMany("Payouts")
                        .HasForeignKey("EventPartyId");
                });

            modelBuilder.Entity("GarageSaleApp.Domain.Sale", b =>
                {
                    b.HasOne("GarageSaleApp.Domain.GarageSaleEvent", "Event")
                        .WithMany("Sales")
                        .HasForeignKey("EventId");
                });

            modelBuilder.Entity("GarageSaleApp.Domain.SaleLineItem", b =>
                {
                    b.HasOne("GarageSaleApp.Domain.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId");

                    b.HasOne("GarageSaleApp.Domain.Sale", "Sale")
                        .WithMany("LineItems")
                        .HasForeignKey("SaleId");
                });
#pragma warning restore 612, 618
        }
    }
}
